registry:
  restart: always
  image: registry:2
  hostname: registry
  domainname: cloud.com
  ports:
    - 443:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /kubernetes_cd/registry/data:/var/lib/registry
    - /kubernetes_cd/registry/certs:/certs
    - /kubernetes_cd/registry/auth:/auth
jenkins:
  restart: always
  build: jenkins/
  links:
    - registry
  ports:
    - 8080:8080
    - 50000:50000
  volumes:
    - /kubernetes_cd/jenkins/data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /kubernetes_cd/registry/certs/domain.crt:/etc/docker/certs.d/registry.cloud.com/ca.crt
  extra_hosts:
    - registry.cloud.com:${REGISTRY_PORT_5000_TCP_ADDR}